name: Rust static build
on:
  push:
    branches:
      - workflow-testing
jobs:
  build:
    name: build for all platforms
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      BINARY_NAME: rust-test1
    steps:
    - uses: actions/checkout@v2
    - name: Build-musl Linux aarch64
      uses: shogan/rust-musl-action@master
      with:
        args: cargo build --target aarch64-unknown-linux-musl --release
    - name: Build-musl Linux x86
      uses: shogan/rust-musl-action@master
      with:
        args: cargo build --target x86_64-unknown-linux-musl --release
